/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
Author: VISIONNEW (https://sketchfab.com/VISIONNEW)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-dc3daa4c867a4582b6aaeeb484ca7bf4
Title: LAPTOP
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.polySurface1SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.polySurface5SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.polySurface5SG1} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop.glb')
