/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tripod.glb 
Author: jmadden64 (https://sketchfab.com/jmadden64)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/simple-cinema-camera-on-a-tripod-05277d8574704c10a83b7e5f5eacac97
Title: Simple cinema camera on a tripod
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tripod(props) {
  const { nodes, materials } = useGLTF('/tripod.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.08, -0.406, 0.004]} rotation={[0, 0.353, 0]} scale={[69, 3, 3]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.013']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tripod.glb')
